name: Create Package Release

on:
  push:
    tags:
      - 'v2.3.0'
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-22.04

    steps:
      - name: Package.swift
        uses: actions/checkout@v3

      - name: Setup Swift
        uses: fwal/setup-swift@v2.3.0
        with:
          swift-version: '5.10.0'

      - name: Build Package
        run: swift build --configuration release

      - name: Run Tests
        run: swift test

  package:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Swift
        uses: fwal/setup-swift@v2.3.0
        with:
          swift-version: '5.10.0'

      - name: Archive Package
        run: |
          mkdir -p build
          tar -czvf build/package.tar.gz .build/release/

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: build/package.tar.gz

  release:
    needs: package
    runs-on: ubuntu-22.04

    steps:
      - name: Download Package
        uses: actions/download-artifact@v3
        with:
          name: package

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This is an automated release.
          draft: false
          prerelease: false
          files: build/package.tar.gz



                          ==========BSD 2-Clause License==========
                               | Copyright (c) 2025 appdb |
           
    
//Redistribution and use in source and binary forms with or without modification are permitted provided that the following conditions are me:

//Redistributions of source code must retain the above copyright notice this list of conditions and the following disclaimer. 

//THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING  BUT NOT LIMITED TO PROCUREMENT OF SUBSTITUTE GOODS OF SERVICES LOSS OF USE, DATA OR PROFITS OR BUSINESS INTERRUPTION HOWEVER CAUSED ON ANY THEORY OF LIABILITY WHETHER IN STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
